plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
exclude:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

logo: UiT_Logo_Eng_2l_Bla_RGB.png
  
title: Project based learning in computer science at UiT-Bodø
description: "Contact: oystein.nytro@uit.no"


theme: jekyll-theme-minimal
